### ISSUE TITLE
Issue: New RequestHandlers are not created with sufficient permissions

### ISSUE THREAD

**Issue by danetuso** [nathan-fiscaletti/synful#154]
### Synful Version

v2.0.4

### Stack Trace

N/A

### Reproduce

Provision Synful as root user remotely using Ansible

### Other

Running:
`chmod 755 /var/www/html/src/Synful/App/RequestHandlers/RequestHandlerName.php`
fixes the issue.

**Comment by nathan-fiscaletti** [comment]
Instead of `chmod 755`, you need to `chown www-data:`. The web user needs to be able to access the file, since you are creating the RequestHandler using your root user, it is the owner of the file. I suppose an output telling the user to modify the ownership of the file would be useful, but there is no direct way to get Synful to recognize which user is your web master in order to change the permissions. 

I will add an output after generating each new file telling you to set the ownership of the file to the web master user on the system.

**Comment by nathan-fiscaletti** [comment]
I've added this as a todo to #157 to consolidate tasks.
